services:
  vault:
    image: hashicorp/vault:1.18

    container_name: project3_vault

    cap_add:
      - IPC_LOCK

    ports:
      - "8200:8200"

    environment:
      VAULT_ADDR: http://127.0.0.1:8200

    command:
      vault server -config=/vault/config/config.hcl

    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
      - ./data:/vault/file
      - ./keys:/vault/keys

    networks:
      - vault_net

networks:
  vault_net:
