name: Project3 CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker Compose
        run: docker compose config

      - name: Build containers
        run: docker compose build

      - name: Deploy
        run: |
          docker compose down
          docker compose up -d

      - name: Show containers
        run: docker ps
