name: Project3 CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load local environment file
        run: |
          cp ~/Desktop/project3/.env .env

      - name: Check Docker Compose
        run: docker compose config

      - name: Build application
        run: docker compose build

      - name: Deploy application
        run: docker compose up -d

      - name: Check containers
        run: docker ps
